# Generated by Django 3.2.4 on 2021-06-05 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('duration', models.CharField(choices=[('short', '0 - 30min'), ('medium', '31 - 45 min'), ('long', '46 - 60 min')], max_length=6)),
                ('recorded_time', models.DurationField(default=datetime.timedelta(0))),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
